import json
from datetime import datetime, timezone

OUTPUT_FILE = "data.json"


def now_iso():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')


def build_payload():
    return {
        "lastUpdated": now_iso(),
        "risks": [
            {
                "title": "Threat monitoring pipeline active",
                "severityText": "P3 LOW",
                "severityColor": "amber",
                "status": "VERIFIED",
                "statusColor": "emerald",
                "timestamp": now_iso(),
                "description": "Initial fallback dataset generated successfully. Replace this logic later with live feed processing if needed.",
                "links": []
            }
        ],
        "timeline": [
            {
                "date": datetime.now(timezone.utc).strftime('%b %d'),
                "loc": "System",
                "event": "data.json generated by GitHub Actions",
                "impact": "P3 LOW",
                "impactClass": "bg-amber-500/20 text-amber-300 border-amber-500/20"
            }
        ]
    }


if __name__ == '__main__':
    payload = build_payload()
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(f'Created {OUTPUT_FILE}')
